build scripts. kernel fix for mdev automount. init script updates

diff --git a/audio/overlay/etc/init.d/S42node b/audio/overlay/etc/init.d/S42node
--- a/audio/overlay/etc/init.d/S42node
+++ b/audio/overlay/etc/init.d/S42node
@@ -7,69 +7,92 @@ APP_DIR="/www/server/server"
 APP_DIR="/opt/server"
 NODE_APP="server.js"
 DAEMON=$(which node)
-DAEMON_ARGS="/www/server/server/server.js"
-DAEMON_ARGS="/opt/server/server.js"
+OPTS="$APP_DIR/$NODE_APP"
 
-pid_file_exists() {
-    [ -f "$PIDFILE" ]
-}
+
+    
+
+# Sanity checks
+test -f $CONFFILE || exit 0
+
+if [ ! -d $PIDDIR ]
+then
+  mkdir -p $PIDDIR
+fi
+
+if [ ! -x $DAEMON ]; then
+  echo "ERROR: Can't locate $DAEMON."
+  exit 1
+fi
 
 get_pid() {
-    echo "$(cat "$PIDFILE")"
+    if [ -f "$PIDFILE" ]; then
+        cat "$PIDFILE"
+    else
+        echo "No PID yet"
+    fi
 }
 
 is_running() {
-    PID="$(get_pid)"
-    [ -d /proc/$PID ]
+    [ -f "$PIDFILE" ]
 }
 
 start() {
-    export NODE_ENV=$NODE_ENVIROMENT
-    printf "Starting $NAME: "
-    start-stop-daemon -S -q -m -b -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
-    [ $? = 0 ] && echo "OK, started with pid $PIDFILE : $(get_pid)" || echo "FAIL"
+        printf "Starting $NAME: "
+        export NODE_ENV=$NODE_ENVIROMENT
+        cd $APP_DIR
+        start-stop-daemon -S -q -b -m -p $PIDFILE --exec $DAEMON -- $OPTS
+        case "$?" in
+        0)
+            echo "$NAME started (`get_pid`)"
+            exit 0
+        ;;
+        1)
+            echo "$NAME seems to be running (`get_pid`)"
+        ;;
+        2)
+            echo "This is really strange [2]"
+        ;;
+        3)
+            echo "ERROR: $NAME did not start"
+        ;;
+        *)
+            echo "This is really strange [???]"
+    esac
+    exit 1
 }
+
 stop() {
-    printf "Stopping $NAME: "
-    start-stop-daemon -K -q -p $PIDFILE
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+        printf "Stopping $NAME: "
+        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+                && echo "OK" || echo "FAIL"
 }
-restart() {
-    stop
-    sleep 2
-    start
-}
+
 status() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "$NAME is running with pid $PIDFILE : $(get_pid)"
-        else
-            echo "$NAME is stopped, but pid file exists"
-        fi
+    if is_running; then
+        PID=$(get_pid)
+        echo "$NAME is running with pid $PIDFILE : $(get_pid)"
     else
-        echo "$NAME is stopped"
+        echo "$NAME is stopped, but pid file exists"
     fi
 }
 
 case "$1" in
-  start)
-        start
-        ;;
-  stop)
-        stop
-        ;;
-  restart|reload)
-        restart
-        ;;
-  status)
-        status
-        ;;
-  *)
-        echo "Usage: $0 {start|stop|restart}"
-        exit 1
+        start)
+                start
+                ;;
+        stop)
+                stop
+                ;;
+        restart|reload)
+                stop
+                sleep 1
+                start
+                ;;
+        status)
+                status
+                ;;
+        *)
+                echo "Usage: $0 {start|stop|restart}"
+                exit 1
 esac
-
-exit $?
diff --git a/audio/overlay/etc/init.d/S50redis b/audio/overlay/etc/init.d/S50redis
--- a/audio/overlay/etc/init.d/S50redis
+++ b/audio/overlay/etc/init.d/S50redis
@@ -1,39 +1,61 @@
 #!/bin/sh
 NAME=redis
-PIDFILE=/var/run/redis/redis.pid
-CONFFILE=/opt/redis/redis.conf
+DAEMON=/usr/bin/$NAME-server
+PIDDIR=/var/run/$NAME
+PIDFILE=$PIDDIR/$NAME.pid
+CONFFILE=/opt/$NAME/$NAME.conf
+OPTS=$CONFFILE
 
 # Sanity checks
-test -f /opt/redis/redis.conf || exit 0
+test -f $CONFFILE || exit 0
 
-pid_file_exists() {
-    [ -f "$PIDFILE" ]
-}
+if [ ! -d $PIDDIR ]
+then
+  mkdir -p $PIDDIR
+fi
+
+chown -R redis:redis $PIDDIR
+chown -R redis:redis /opt/$NAME
+
+if [ ! -x $DAEMON ]; then
+  echo "ERROR: Can't locate $DAEMON."
+  exit 1
+fi
 
 get_pid() {
-    echo "$(cat "$PIDFILE")"
+    if [ -f "$PIDFILE" ]; then
+        cat "$PIDFILE"
+    else
+        echo "No PID yet"
+    fi
 }
 
 is_running() {
-    PID="$(get_pid)"
-    [ -d /proc/$PID ]
+    [ -f "$PIDFILE" ]
 }
 
 start() {
         printf "Starting $NAME: "
-        start-stop-daemon -S -q -m -b -p var/run/redis/redis.pid -c redis:redis --exec /usr/bin/redis-server -- /opt/redis/redis.conf
-        if pid_file_exists
-        then
-            if is_running
-            then
-                PID=$(get_pid)
-                echo "$NAME is running with pid $PIDFILE : $(get_pid)"
-            else
-                echo "$NAME is stopped, but pid file exists"
-            fi
-        else
-            echo "$NAME is stopped"
-        fi
+        # CONFIGURE PIDFILE IN CONFIG
+        start-stop-daemon -S -q -b -c redis:redis --exec $DAEMON -- $OPTS
+        case "$?" in
+        0)
+            echo "$NAME started (`get_pid`)"
+            exit 0
+        ;;
+        1)
+            echo "$NAME seems to be running (`get_pid`)"
+        ;;
+        2)
+            echo "This is really strange [2]"
+        ;;
+        3)
+            echo "ERROR: $NAME did not start"
+        ;;
+        *)
+            echo "This is really strange [???]"
+    esac
+    exit 1
 }
 
 stop() {
@@ -43,17 +65,11 @@ stop() {
 }
 
 status() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "$NAME is running with pid $PIDFILE : $(get_pid)"
-        else
-            echo "$NAME is stopped, but pid file exists"
-        fi
+    if is_running; then
+        PID=$(get_pid)
+        echo "$NAME is running with pid $PIDFILE : $(get_pid)"
     else
-        echo "$NAME is stopped"
+        echo "$NAME is stopped, but pid file exists"
     fi
 }
 
diff --git a/audio/overlay/etc/init.d/S95mpd b/audio/overlay/etc/init.d/S95mpd
--- a/audio/overlay/etc/init.d/S95mpd
+++ b/audio/overlay/etc/init.d/S95mpd
@@ -1,60 +1,75 @@
 #!/bin/sh
 NAME=mpd
-PIDFILE=/var/run/mpd/mpd.pid
-CONFFILE=/opt/mpd/mpd.conf
+DAEMON=/usr/bin/$NAME
+PIDDIR=/var/run/$NAME
+PIDFILE=$PIDDIR/$NAME.pid
+CONFFILE=/opt/$NAME/$NAME.conf
+OPTS=$CONFFILE
 
 # Sanity checks
-test -f /opt/mpd/mpd.conf || exit 0
+test -f $CONFFILE || exit 0
 
-pid_file_exists() {
-    [ -f "$PIDFILE" ]
-}
+if [ ! -d $PIDDIR ]
+then
+  mkdir -p $PIDDIR
+fi
+
+chown -R mpd:audio $PIDDIR
+chown -R mpd:audio /opt/$NAME
+
+if [ ! -x $DAEMON ]; then
+  echo "ERROR: Can't locate $DAEMON."
+  exit 1
+fi
 
 get_pid() {
-    echo "$(cat "$PIDFILE")"
+    if [ -f "$PIDFILE" ]; then
+        cat "$PIDFILE"
+    else
+        echo "No PID yet"
+    fi
 }
 
 is_running() {
-    PID="$(get_pid)"
-    [ -d /proc/$PID ]
+    [ -f "$PIDFILE" ]
 }
 
 start() {
-        printf "Starting mpd: "
-        start-stop-daemon -S -q -m -b -p $PIDFILE --exec /usr/bin/mpd -- $CONFFILE
-        # start-stop-daemon -S -v -m -p /var/run/mpd/mpd.pid --exec /usr/bin/mpd -- /opt/mpd/mpd.conf
-        if pid_file_exists
-        then
-            if is_running
-            then
-                PID=$(get_pid)
-                echo "$NAME is running with pid $PIDFILE : $(get_pid)"
-            else
-                echo "$NAME is stopped, but pid file exists"
-            fi
-        else
-            echo "$NAME is stopped"
-        fi
+        printf "Starting $NAME: "
+        # CONFIGURE PIDFILE IN CONFIG
+        start-stop-daemon -S -q -b -c mpd:audio --exec $DAEMON -- $OPTS
+        case "$?" in
+        0)
+            echo "$NAME started (`get_pid`)"
+            exit 0
+        ;;
+        1)
+            echo "$NAME seems to be running (`get_pid`)"
+        ;;
+        2)
+            echo "This is really strange [2]"
+        ;;
+        3)
+            echo "ERROR: $NAME did not start"
+        ;;
+        *)
+            echo "This is really strange [???]"
+    esac
+    exit 1
 }
 
 stop() {
-        printf "Stopping mpd: "
+        printf "Stopping $NAME: "
         start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                 && echo "OK" || echo "FAIL"
 }
 
 status() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "$NAME is running with pid $PIDFILE : $(get_pid)"
-        else
-            echo "$NAME is stopped, but pid file exists"
-        fi
+    if is_running; then
+        PID=$(get_pid)
+        echo "$NAME is running with pid $PIDFILE : $(get_pid)"
     else
-        echo "$NAME is stopped"
+        echo "$NAME is stopped, but pid file exists"
     fi
 }
 
